import number from 'helpers/number';

export interface Ope040106Vo {
	// oaHydrocarbDtlId: number;
	// oaHydrocarbId: number;
	// officePlaceOwner: string;
	// officeRentAmount: number;
	// workingStartDate: Date;
	// workingEndDate: Date;
	// workdayPermonth: number;
	// numberOfTank: number;
	// tankCapacity: string;
	// numberUtility: string;
	// orderType: string;
	// orderPayMethod: string;
	// employeePermanent: number;
	// employeeTemporary: number;
	// payMethodOther: string;
	// dailyAcc: string;
	// dailyAccDoc: string;
	// dailyAuditRemark: string;
	// monthlyAcc: string;
	// monthlyAccDoc: string;
	// monthlyAuditRemark: string;
	// monthlyAcc04: string;
	// monthlyAccDoc04: string;
	// monthlyAuditRemark04: string;
	// materail: string;
	// document: number;
	// productProcess: string;
	// productNextime: string;
	// useStartDate: Date;
	// useEndDate: Date;
	// buyOverlimit: string;
	// buyFromIndust: string;
	// buyIndustLicense: string;
	// buyFromImporter: string;
	// buyImporterLicense: string;
	// buyFromAgent: string;
	// buyAgentLicense: string;
	// usedType: string;
	// usedRemark: string;
	// salerType: string;
	// salerCapacity: string;
	// numOfCust: number;
	// goodQuality: string;
	// agentStartDate: Date;
	// agentEndDate: Date;
	// agentOverlimit: string;
	// abuyFromIndust: string;
	// abuyIndustLicense: string;
	// abuyFromImporter: string;
	// aimporterLicense: string;
	// abuyFromAgent: string;
	// abuyAgentLicense: string;
	// asaleToAgent: string;
	// asaleAgentLicense: string;
	// asaleToUser: string;
	// asaleUserLicense: string;
	// sentToAgent: string;
	// agentRemark: string;
	// sentToUser: string;
	// otherRemark: string;
	// customers?: Ope040106CustomerVo[];
	// custdeles?: Ope040106CustomerVo[];
	// auditResult: string;

	oaAlcoholDtlId: number;
	oaAlcoholId: number;
	licenseMenufac: string;
	licenseMenufacRemark: string;
	licenseType2: string;
	licenseType2Remark: string;
	achDegree: string;
	achDegreeRemark: string;
	achCapacity: string;
	achCapacityRemark: string;
	achApprove: string;
	achApproveRemark: string;
	achPrice: string;
	achPriceRemark: string;
	achStamp: string;
    achStampRemark: string;
	placeStatus: string;
	placeStatusRemark: string;
	eqmTank: string;
	eqmTankNum: number;
	eqmDistil: string;
	eqmDistilNum: number;
	eqmPacking: string;
	eqmPackingNum: number;
	audit0701: string;
	audit0701Remark: string;
	audit07021: string;
	audit07021Remark: string;
	audit07022: string;
	audit07022Remark: string;
	equipmentUsed: string;
	equipmentUsedRemark: string;
	auditOther: string;
	auditSuggestion: string;
	eqmTankStatus: string;
	eqmDistilStatus: string;
	eqmPackingStatus: string;

}

export interface Ope040106CustomerVo {
	oaHydrocarbCustId: number;
	oaHydrocarbId: number;
	custName: string;
	address: string;
	mobile: string;
}

export interface Ope040106ButtonVo {
	oaAlcoholId: number;
	oaPlanId: number;
	oaAlcoholDtlId: number;
	oaCuslicenseId: number;
	oaCustomerId: number;
	licenseNo: string;
	licenseType: string;
	oldCustomer: string;
}
export interface AlcoholDtl {
	oaAlcoholDtlId: number;
	oaAlcoholId: number;
	licenseMenufac: string;
	licenseMenufacRemark: string;
	licenseType2: string;
	licenseType2Remark: string;
	achDegree: string;
	achDegreeRemark: string;
	achCapacity: string;
	achCapacityRemark: string;
	achApprove: string;
	achApproveRemark: string;
	achPrice: string;
	achPriceRemark: string;
	placeStatus: string;
	placeStatusRemark: string;
	eqmTank: string;
	eqmTankNum: number;
	eqmDistil: string;
	eqmDistilNum: number;
	eqmPacking: string;
	eqmPackingNum: number;
	audit0701: string;
	audit0701Remark: string;
	audit07021: string;
	audit07021Remark: string;
	audit07022: string;
	audit07022Remark: string;
	equipmentUsed: string;
	equipmentUsedRemark: string;
	auditOther: string;
	auditSuggestion: string;
}